# Generated by Django 3.2.2 on 2021-05-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20210508_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
